<?php

/**
 * @file
 * Contains openweathermap.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function openweathermap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the openweathermap module.
    case 'help.page.openweathermap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Retrieves weather forecast data from openweathermap.org and displays on the page.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function openweathermap_theme($existing, $type, $theme, $path) {
  return [
    'openweathermap_controller_theme' => [
      'render element' => 'children',
      'template' => 'openweathermap-controller',
      'path' => $path . '/templates',
      'variables' => [],
    ],
    'openweathermap_mail_theme' => [
      'render element' => 'children',
      'template' => 'openweathermap-mail',
      'path' => $path . '/templates',
      'variables' => [
        'body' => 'body',
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function openweathermap_mail($key, &$message, $params) {
  if (isset($params['headers'])) {
    $message['headers'] = array_merge($message['headers'], $params['headers']);
  }
  switch ($key) {
    case 'openweathermap_mail_theme':
      $message['from'] = $params['from'];
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openweathermap_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['#submit'][] = 'openweathermap_user_login_submit';
}

/**
 * Form submission handler for user_login_form().
 * Redirects the user to the dashboard after logging in.
 */
function openweathermap_user_login_submit(&$form, FormStateInterface $form_state) {
  $url = Url::fromUri('internal:/');

  // Check if a destination was set, probably on an exception controller.
  // @see \Drupal\user\Form\UserLoginForm::submitForm()
  $request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!$request->request->has('destination')) {
    $form_state->setRedirectUrl($url);
  }
  else {
    $request->query->set('destination', $request->request->get('destination'));
  }
}
